apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app-deployment
  namespace: 04--pod
  labels:
    app: posts-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: posts-app
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
      - name: posts-app-container
        image: image-name
        ports:
        - containerPort: 80
