name: CI
run-name: ${{github.actor}} is running this action
on: [pull_request, push]
defaults:
  run:
    working-directory: ./my-app
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build 
        run: npm run build
      # This step runs if any of the previous steps fail
      - name: Create GitHub Issue on Failure
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADJECTIVE: great