name: CI
run-name: ${{github.actor}} is running this action
on: [pull_request]
defaults:
  run:
    working-directory: ./my-app
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build 
        run: npm build


    