name: OWASP ZAP Integration with GitHub Actions

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'http://qkshare.jonnoyip.com'
