name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://qkshare.jonnoyip.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
